### ISSUE TITLE
Enhance BitBucket Pull Feedback

### ISSUE THREAD

**Issue by kmcdon83** [checkmarx-ts/cx-flow#13]
Investigate and implement additional capabilities within BitBucket Pull Request feedback
 
- [x] Block Merge after scan completes, based on filter/policy criteria
- [ ] Provide diff view, to help determine if current commit/pull has introduced the finding
- [ ] Source snippet highlights as a comment. This would need to occur at the commit level (i.e. Violation comments as a reviewer on the file/commit). Checkmarx BB Service account would be a "reviewer" of the code. References:

https://wiki.jenkins.io/display/JENKINS/Violation+Comments+to+Bitbucket+Server+Plugin

**Comment by kmcdon83** [comment]
For Bitbucket Server (6.x+) 
[ ] - Add Approver (cxflow user)
[ ] - Add Task (Checkmarx Scan)

**Comment by nleach999** [comment]
My reference was not for issue #13 in this repository.  It was for the SDK repository.

**Comment by gerron** [comment]
> 
> 
> My reference was not for issue #13 in this repository. It was for the SDK repository.

@nleach999 Given this response, does cx-flow support merge blocking with Bitbucket? Or should this issue be reopened?

**Comment by kmcdon83** [comment]
Was closed in error

**Comment by kmcdon83** [comment]
Moved to https://github.com/checkmarx-ltd/cx-flow/issues/171
