### ISSUE TITLE
Automated Integration Tests

### ISSUE THREAD

**Issue by kmcdon83** [checkmarx-ts/cx-flow#22]
Create pipeline of automated integration testing for validating various 3rd party APIs are working as desired
- [ ] GitHub
- [ ] GitLab
- [ ] BitBucket
- [ ] AzureDevOps
- [ ] JIRA

**Comment by MithileshPawar** [comment]
Closing this issue since it has been moved to another repo.
https://github.com/checkmarx-ltd/cx-flow/issues/162
