### ISSUE TITLE
Block Merge after scan completion on PR/MR

### ISSUE THREAD

**Issue by kmcdon83** [checkmarx-ts/cx-flow#24]
Add the ability to block merge based on scan results filter for:

- [x] GitHub
- [ ] GitLab
- [ ] Azure DevOps

**Comment by kmcdon83** [comment]
This implementation is completed for GitHub integration.
A new configuration option is now available per repo config block:
github: ... block-merge: true error-merge: true

block-merge will block the merge during scan execution.
error-merge will fail the status , therefore blocking the merge. Closing and opening the PR again would be required to trigger the flow again. In the event the filter criteria for issues in CxFlow has any results, then this is considered a violation and will be a failure (based on severity, vulnerability type, cwe, status in Checkmarx, etc).

Block Merge (during scan):
image

Error Merge (based on any results meeting filter criteria/policy):
image

**Comment by gerron** [comment]
@kmcdon83 will blocking merges be supported for Bitbucket as well?

**Comment by MithileshPawar** [comment]
Closing this issue since it has been moved to another repo.
https://github.com/checkmarx-ltd/cx-flow/issues/160
