### ISSUE TITLE
Validate TFS/Azure DevOps Implementations

### ISSUE THREAD

**Issue by kmcdon83** [checkmarx-ts/cx-flow#28]
Ensure CxFlow WebHooks and WorkItems work with the various flavors of Azure DevOps / TFS Server

- [x] Azure DevOps Cloud
- [ ] Azure DevOps 2019 Server
- [ ] TFS/Azure DevOps 2018 Server
- [x] TFS/Azure DevOps 2017 Server
- [ ] TFS/Azure DevOps 2015 Server

**Comment by skoyev** [comment]
Moved into ltd branch
