### ISSUE TITLE
Config As Code

### ISSUE THREAD

**Issue by kmcdon83** [checkmarx-ts/cx-flow#36]
Introduce Configuration as Code capability to override CxFlow settings

- [x] GitHub
- [x] GitLab
- [ ] Azure DevOps - https://dev.azure.com/{org}/_apis/git/repositories/{repoid}/items?scopePath={file}&download=true&api-version=5.1
- [ ] BitBucket Server
- [ ] BitBucket Cloud

**Comment by kmcdon83** [comment]
GitHub/GitLab capability now complete

**Comment by MithileshPawar** [comment]
Closing this issue since it has been moved to another repo.
https://github.com/checkmarx-ltd/cx-flow/issues/149
