### ISSUE TITLE
Automated Code Profiling

### ISSUE THREAD

**Issue by kmcdon83** [checkmarx-ts/cx-flow#37]
Add capability to scan repository for code content and finger print the application to help determine a preset/scan ruleset to use automatically

- [x] GitHub
- [x] GitLab
- [ ] Azure DevOps - https://dev.azure.com/{acct}/{project}/_apis/projectanalysis/languagemetrics
- [ ] BitBucket Server
- [ ] BitBucket Cloud

**Comment by kmcdon83** [comment]
GitHub/GitLab Capability now complete

**Comment by MithileshPawar** [comment]
Closing this issue since it has been moved to another repo.
https://github.com/checkmarx-ltd/cx-flow/issues/148
