### ISSUE TITLE
Develop External Credential Implementation

### ISSUE THREAD

**Issue by kmcdon83** [checkmarx-ts/cx-flow#40]
Introduce the capability of externalizing credential injection.  Some examples are:

- [ ] HashiCorp's Vault
- [ ] KeyStore
- [ ] AWS SSM Parameter Store
- [ ] Many more

**Comment by MithileshPawar** [comment]
Closing this issue since it has been moved to another repo.
https://github.com/checkmarx-ltd/cx-flow/issues/145
