### ISSUE TITLE
Allow for external script (Groovy) for Issue Descriptions

### ISSUE THREAD

**Issue by kmcdon83** [checkmarx-ts/cx-flow#42]
Allow for external script (Groovy) for Issue Descriptions

**Comment by GeekMasher** [comment]
Where do we envision the configuration for this Groovy script to be?

I suggest under `cx-flow` or/and per bug tracker implementation to allow different issue descriptions per service (the second would take priority). This would be an optional property.

The per implementation is more for cases where organisations have multiple different services which require possibly their own description format for each service and don't need two separate CxFlow instances to achieve this. This could also be achieved if we pass in the bug tracking system into the Groovy data binding as run-time.

**Proposed Example:**
```
cx-flow:
  // ...
  // The name of the property is subject to change
  script-issueDescription: "IssueDescription.groovy"
```

**Comment by kmcdon83** [comment]
@GeekMasher, I agree with it being under cx-flow block as all the logic for the Issue trackers (except for jira) come from:
https://github.com/checkmarx-ts/cx-flow/blob/develop/src/main/java/com/checkmarx/flow/utils/ScanUtils.java#L411
**JIRA:**  https://github.com/checkmarx-ts/cx-flow/blob/develop/src/main/java/com/checkmarx/flow/service/JiraService.java#L740

Alternatively, we could add to the repo specific (and JIRA) configs, so each system could use it's own template.

What is your vote?

To support different content types we can plan to incorporate template functionality (not scripting) in the config as code.  My preference is we deliver something that is single description format to start and plan to enhance.

Lastly, yaml is typically has camel case converted to dashes:
script-issueDescription -> script-issue-description

**Comment by skoyev** [comment]
Moved into ltd branch
