### ISSUE TITLE
setting breakbuild=true causes error (code 10) even if 0 results

### ISSUE THREAD

**Issue by N3D4U2C** [checkmarx-ts/cx-flow#84]
When the scan completes and  0 vulnerabilites of any severity are found, IF the breakbuild flag is set to true in the config file, we get an error message (Code 10).  

If breakbuild=false, then we get past that error message.  Please fix so when breakbuild=true AND there are 0 results, the process completes successfully.

**Comment by kmcdon83** [comment]
Closing as we cannot reproduce.  Please ensure the 1.5.4 version is downloaded recently.  There are changes applied with the same version number as we prepare for an official release.
