### ISSUE TITLE
github webhook fails with PRs from forked repositories

### ISSUE THREAD

**Issue by milo-minderbinder** [checkmarx-ts/cx-flow#89]
When using CxFlow in web mode and GitHub webhooks enabled, when a pull request to merge a branch from a forked repository onto the CxFlow/source branch, CxFlow will fail in one of two ways:
1. If the forked branch name/ref name does not exist in the source/CxFlow repository, a `GitHubClientRunTimeException` is thrown and not handled, and the CxFlow PR scan & processing will fail silently (no comment is added to the PR indicating that a scan was started), because the CxFlow service will get an unsuccessful response from the GitHub contents API endpoint since it tries to pull the ref/branch name in the CxFlow repo (instead of the forked repo).
2. If the the forked branch name/ref name _does_ exist in the source/CxFlow repository, the webhook processing will succeed, but likely erroneously, unless the forked repo's branch and the source/origin repo's branch are up-to-date/equal. If they do _not_ refer to the exact same commit, then CxFlow will actually be scanning the source/CxFlow repo's commits that correspond to the ref name, and _not_ the forked version's commits as expected/intended.

**_EDIT_**:
At any rate, issues described below notwithstanding, a (relatively) simple fix for the specific issue with forks is to change the lines [here](https://github.com/checkmarx-ts/cx-flow/blob/0986e5b9eff7d369a6666717e1c38e54465ad4db/src/main/java/com/checkmarx/flow/controller/GitHubController.java#L200-L204) to use the value from `pull_request.head.clone_url` in the request body instead of `repository.clone_url`. This may cause unexpected errors if the GitHub OAuth app token or personal OAuth token used by CxFlow doesn't have read permissions on the HEAD repo, but I don't see an easy way to resolve that, and anyway it's beyond the scope of this specific issue.

**Comment by milo-minderbinder** [comment]
Upon further review, I actually think this issue is a result of a more significant issue with the underlying PR event processing flow. From an initial review of the source, I see that the `ScanRequest` object is built with `repoUrlWithAuth` set to the _base_ branch's clone URL (actually, the clone URL from the top-level `repository` object in the pull request event body instead of the `clone_url` field of the `pull_request.base` object, which should probably be used instead). Besides checking that the `merge_ref` name matches any branch filters, the pull request head (the commit(s) to be merged) is not used anymore except to set the branch to clone/scan.

_However_, this means that besides the issue described here initially (if the merge branch ref name doesn't exist in the base repo then checkout will fail), more importantly, the code actually scanned will not actually be the code as it would be if _merged_. What _should_ happen is that the base branch should be cloned, then the head (the branch to be merged) should be merged in, and then the merged code should be scanned.

In the current state, any issues that have been fixed in the base branch, but which still exist in the merge branch (for example because they're unrelated to the code changes in the PR), will still be reported in the PR scan erroneously. In other words, unless you require all PRs to be up-to-date with the base branch _and_ only allow merges which are fast-forwards only (i.e. doesn't matter if the branches can be successfully merged without conflicts, they _must_ be mergeable without making a merge commit), then the scan results for the commit event may be very different from the expected scan results per the pull request event.

**Comment by kmcdon83** [comment]
@milo-minderbinder we will investigate and get a fix asap.
