### ISSUE TITLE
Jira custom fields not loading correctly

### ISSUE THREAD

**Issue by scottylaw** [checkmarx-ts/cx-flow#97]
When attempting to use a Jira label tracker other than the default 'labels' I was getting the following exception:

`com.atlassian.jira.rest.client.api.RestClientException: org.codehaus.jettison.json.JSONException: Null key.`

What I discovered was that the loadCustomFields method in the JiraService is only retrieving fields from the very first CimProject returned from Jira instead of filtering for the project that was configured in the yaml (and the issue type). I updated the GetCreateIssueMetadataOptionsBuilder to include filters for the Jira project and issue type and that resolved my issue.

```java
private void loadCustomFields() {
        log.debug("Loading all custom fields");
        GetCreateIssueMetadataOptions options;
        options = new GetCreateIssueMetadataOptionsBuilder()
                .withProjectKeys(jiraProperties.getProject())
                .withIssueTypeNames(jiraProperties.getIssueType())
                .withExpandedIssueTypesFields()
                .build();
        Iterable<CimProject> metadata = this.issueClient.getCreateIssueMetadata(options).claim();
        metadata.forEach(cim -> {
            cim.getIssueTypes().forEach(issueTypes -> {
                issueTypes.getFields().forEach((id, value) -> {
                    String name = value.getName();
                    this.customFields.put(name, id);
                });
            });
        });
    }```

**Comment by kmcdon83** [comment]
This logic was reworked.  You must have pulled just before this was applied.  We had to shuffle this logic as to when the load took place.  Some were having performance issues as well.
https://github.com/checkmarx-ts/cx-flow/blob/develop/src/main/java/com/checkmarx/flow/service/JiraService.java#L747
